### ISSUE TITLE
awml-event inside awml-options has wrong context

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/AWML#11]
Defining `<awml-event>` inside `<awml-options>` results in `this` inside callback points to parent widget of `<awml-options>` which should be `<awml-root>` in most cases.

**Comment by arneg** [comment]
This is currently not supported.

**Comment by arneg** [comment]
After thinking about this, I guess we could add something similar to `awml-options` called `awml-events`. The syntax could look like this

`<awml-events name=foo>
{
click: function(ev) { return false; },
....
}
</awml-events>`

And similar to `awml-options`, those would then be added to a widget using events='foo, ...'.

**Comment by boomshop** [comment]
Sounds great!
