### ISSUE TITLE
Attribute "loop" for awml-clone

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/AWML#13]
Looping awml-clones could make code cleaner:

`<awml-clone template=whatever prefix="local:objects/%d/" loop=16 start=1></awml-clone>`

compared to

`<awml-clone template=whatever prefix="local:objects/1/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/2/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/3/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/4/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/5/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/6/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/7/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/8/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/9/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/10/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/11/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/12/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/13/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/14/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/15/"></awml-clone>
<awml-clone template=whatever prefix="local:objects/16/"></awml-clone>`

Imagine 64 objects.

**Comment by arneg** [comment]
We now have the `transform-template` attribute which can be used to install a method to transform a given template. This is more flexible than having a simple loop and should be able to handle this and many more use-cases.
